/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xiaomi;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author masrc
 */
public class dataform extends javax.swing.JFrame {

    String sql = "select * from handphone";
    int dragxmouse;
    int dragymouse;
    public dataform() throws SQLException {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        showTable(sql);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        totalhpTxt = new javax.swing.JTextField();
        totalincomeTxt = new javax.swing.JTextField();
        toMenuButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        orderNameTxt = new javax.swing.JTextField();
        areaTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tableData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nomor Pesanan", "Nama Pemesan", "Tipe Handphone", "Harga", "Lama Cicilan", "Cicilan/Bulan"
            }
        ));
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(62, 260, 1160, 260);

        totalhpTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalhpTxt.setBorder(null);
        getContentPane().add(totalhpTxt);
        totalhpTxt.setBounds(1020, 540, 190, 30);

        totalincomeTxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalincomeTxt.setBorder(null);
        getContentPane().add(totalincomeTxt);
        totalincomeTxt.setBounds(1020, 590, 190, 30);

        toMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/12.png"))); // NOI18N
        toMenuButton.setBorder(null);
        toMenuButton.setContentAreaFilled(false);
        toMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toMenuButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toMenuButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                toMenuButtonMouseReleased(evt);
            }
        });
        toMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(toMenuButton);
        toMenuButton.setBounds(70, 550, 320, 80);

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/cari1.png"))); // NOI18N
        searchButton.setBorder(null);
        searchButton.setContentAreaFilled(false);
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                searchButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchButtonMouseReleased(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton);
        searchButton.setBounds(270, 170, 150, 80);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/all data1.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setContentAreaFilled(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonMouseReleased(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(190, 180, 110, 60);

        orderNameTxt.setBorder(null);
        getContentPane().add(orderNameTxt);
        orderNameTxt.setBounds(300, 80, 190, 20);

        areaTxt.setBorder(null);
        getContentPane().add(areaTxt);
        areaTxt.setBounds(300, 140, 190, 21);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/hapus1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 190, 120, 40);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 1250, 620);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/data.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1290, 670);

        setSize(new java.awt.Dimension(1308, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void toMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toMenuButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/1212.png"));
        toMenuButton.setIcon(b);
    }//GEN-LAST:event_toMenuButtonMouseEntered

    private void toMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toMenuButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/12.png"));
        toMenuButton.setIcon(b);
    }//GEN-LAST:event_toMenuButtonMouseExited

    private void toMenuButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toMenuButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/12.png"));
        toMenuButton.setIcon(b);
    }//GEN-LAST:event_toMenuButtonMousePressed

    private void toMenuButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toMenuButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/1212.png"));
        toMenuButton.setIcon(b);
    }//GEN-LAST:event_toMenuButtonMouseReleased

    private void toMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toMenuButtonActionPerformed
        option option = new option();
        option.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_toMenuButtonActionPerformed

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/cari11.png"));
        searchButton.setIcon(b);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/cari1.png"));
        searchButton.setIcon(b);
    }//GEN-LAST:event_searchButtonMouseExited

    private void searchButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/cari1.png"));
        searchButton.setIcon(b);
    }//GEN-LAST:event_searchButtonMousePressed

    private void searchButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/cari11.png"));
        searchButton.setIcon(b);
    }//GEN-LAST:event_searchButtonMouseReleased

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/all data11.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/all data1.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseExited

    private void deleteButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/all data1.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMousePressed

    private void deleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/all data11.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseReleased

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        if(orderNameTxt.getText().isEmpty() && areaTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, 
                    "Masukan data yang ingin di cari", "Error", 
                    JOptionPane.ERROR_MESSAGE);
            showTable(sql);
        }else if(orderNameTxt.getText().isEmpty()){
            //kode untuk mencari berdasarkan area
            showTable("SELECT * FROM handphone WHERE tipe LIKE '%" 
                    + areaTxt.getText() + "%'");
        }else if(areaTxt.getText().isEmpty()){
            //kode mencari berdasarkan nama
            showTable("SELECT * FROM handphone WHERE name LIKE '%" 
                    + orderNameTxt.getText() + "%'");
        }else {
            //kode untuk untuk mencari berdasarkan nama dan area
            showTable("SELECT * FROM handphone WHERE name LIKE '%" 
                    + orderNameTxt.getText() + "%' AND tipe LIKE '%" 
                    + areaTxt.getText() + "%'");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        areaTxt.setText("");
        showTable(sql);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/hapus11.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/hapus1.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/hapus1.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/hapus11.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {    
            sql="DELETE FROM handphone WHERE name='"+ orderNameTxt.getText() +"'";
            orderNameTxt.requestFocus();
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            s.execute(sql);
            showTable(sql);
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di hapus");
        } catch (SQLException ex) {
            Logger.getLogger(dataform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void showTable(String sql){
        try{
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            DefaultTableModel tableModel;
            tableModel = (DefaultTableModel)tableData.getModel();
            tableModel.getDataVector().removeAllElements();
            while(r.next()){
                tableModel.addRow(new Object[] {
                    r.getString(1), r.getString(2), r.getString(3), r.getString(4), r.getString(5), r.getString(6)
                });
                long totalIncome = 0;
                int totalHp;
                totalHp = r.getRow();
                
                for(int i = 0; i < totalHp; i++){
                    long income = Long.parseLong((String) tableModel.getValueAt(i, 3));
                    totalIncome += income;
                }
                
                totalhpTxt.setText("" + totalHp);
                totalincomeTxt.setText("" + totalIncome);
                    
            }
        } catch (SQLException ex){
            Logger.getLogger(dataform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dataform().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dataform.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaTxt;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable tableData;
    private javax.swing.JButton toMenuButton;
    private javax.swing.JTextField totalhpTxt;
    private javax.swing.JTextField totalincomeTxt;
    // End of variables declaration//GEN-END:variables
}
