/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xiaomi;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author masrc
 */
public class pembayaran extends javax.swing.JFrame {

    int dragxmouse;
    int dragymouse;
    private Object ex;
    public pembayaran() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        installmentAmountTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        installmentMonthTxt = new javax.swing.JTextField();
        agreementCbx = new javax.swing.JCheckBox();
        areaCombobox = new javax.swing.JComboBox<>();
        processButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        orderNameTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        orderNameTxt.setBorder(null);
        orderNameTxt.setOpaque(false);
        getContentPane().add(orderNameTxt);
        orderNameTxt.setBounds(270, 110, 270, 30);

        priceLandTxt.setEditable(false);
        priceLandTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        priceLandTxt.setBorder(null);
        priceLandTxt.setOpaque(false);
        getContentPane().add(priceLandTxt);
        priceLandTxt.setBounds(270, 170, 270, 30);

        priceTxt.setEditable(false);
        priceTxt.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        priceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        priceTxt.setBorder(null);
        priceTxt.setOpaque(false);
        getContentPane().add(priceTxt);
        priceTxt.setBounds(540, 330, 260, 30);

        DPTxt.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        DPTxt.setBorder(null);
        DPTxt.setOpaque(false);
        getContentPane().add(DPTxt);
        DPTxt.setBounds(540, 382, 260, 30);

        installmentAmountTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        installmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        installmentAmountTxt.setBorder(null);
        installmentAmountTxt.setOpaque(false);
        getContentPane().add(installmentAmountTxt);
        installmentAmountTxt.setBounds(540, 440, 260, 30);

        ppnTxt.setEditable(false);
        ppnTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ppnTxt.setBorder(null);
        ppnTxt.setOpaque(false);
        getContentPane().add(ppnTxt);
        ppnTxt.setBounds(540, 492, 260, 30);

        installmentMonthTxt.setEditable(false);
        installmentMonthTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        installmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        installmentMonthTxt.setBorder(null);
        installmentMonthTxt.setOpaque(false);
        getContentPane().add(installmentMonthTxt);
        installmentMonthTxt.setBounds(540, 550, 260, 30);

        agreementCbx.setBorder(null);
        agreementCbx.setOpaque(false);
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });
        getContentPane().add(agreementCbx);
        agreementCbx.setBounds(850, 550, 93, 25);

        areaCombobox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "Redmi Note 11T 5G", "Xiaomi 11T Pro", "Redmi 10", "POCO X3 GT", "Black Shark 4", "POCO M3 Pro 5G", "Xiaomi Mi 11 Ultra", "Redmi Note 10s", "POCO F3", "POCO F3 Pro" }));
        areaCombobox.setBorder(null);
        areaCombobox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        areaCombobox.setOpaque(false);
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });
        getContentPane().add(areaCombobox);
        areaCombobox.setBounds(260, 222, 280, 40);

        processButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/9.png"))); // NOI18N
        processButton.setBorder(null);
        processButton.setContentAreaFilled(false);
        processButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        processButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                processButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                processButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                processButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                processButtonMouseReleased(evt);
            }
        });
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        getContentPane().add(processButton);
        processButton.setBounds(420, 610, 200, 60);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/10.png"))); // NOI18N
        saveButton.setBorder(null);
        saveButton.setContentAreaFilled(false);
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                saveButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saveButtonMouseReleased(evt);
            }
        });
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(600, 610, 200, 60);

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/11.png"))); // NOI18N
        deleteButton.setBorder(null);
        deleteButton.setContentAreaFilled(false);
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteButtonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteButtonMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                deleteButtonMouseReleased(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(800, 610, 170, 60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/kembali2.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 600, 210, 80);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel1MouseDragged(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 60, 1250, 630);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/xiaomi/images/option.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 0, 1300, 730);

        setSize(new java.awt.Dimension(1314, 744));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragxmouse,y-dragymouse);
        System.out.println(x+","+y);
    }//GEN-LAST:event_jLabel1MouseDragged

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        dragxmouse = evt.getX();
        dragymouse = evt.getY();
    }//GEN-LAST:event_jLabel1MousePressed

    private void processButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/99.png"));
        processButton.setIcon(b);
    }//GEN-LAST:event_processButtonMouseEntered

    private void processButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/9.png"));
        processButton.setIcon(b);
    }//GEN-LAST:event_processButtonMouseExited

    private void processButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/9.png"));
        processButton.setIcon(b);
    }//GEN-LAST:event_processButtonMousePressed

    private void processButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_processButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/99.png"));
        processButton.setIcon(b);
    }//GEN-LAST:event_processButtonMouseReleased

    private void saveButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/1010.png"));
        saveButton.setIcon(b);
    }//GEN-LAST:event_saveButtonMouseEntered

    private void saveButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/10.png"));
        saveButton.setIcon(b);
    }//GEN-LAST:event_saveButtonMouseExited

    private void saveButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/10.png"));
        saveButton.setIcon(b);
    }//GEN-LAST:event_saveButtonMousePressed

    private void saveButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/1010.png"));
        saveButton.setIcon(b);
    }//GEN-LAST:event_saveButtonMouseReleased

    private void deleteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/1111.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseEntered

    private void deleteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/11.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseExited

    private void deleteButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/11.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMousePressed

    private void deleteButtonMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/1111.png"));
        deleteButton.setIcon(b);
    }//GEN-LAST:event_deleteButtonMouseReleased

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch(areaCombobox.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                priceTxt.setText("");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 1:
                priceLandTxt.setText("6000000");
                priceTxt.setText("6000000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 2:
                priceLandTxt.setText("5999000");
                priceTxt.setText("5999000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 3:
                priceLandTxt.setText("1999000");
                priceTxt.setText("1999000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 4:
                priceLandTxt.setText("4399000");
                priceTxt.setText("4399000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 5:
                priceLandTxt.setText("7499000");
                priceTxt.setText("7499000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 6:
                priceLandTxt.setText("2599000");
                priceTxt.setText("2599000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 7:
                priceLandTxt.setText("16999000");
                priceTxt.setText("16999000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 8:
                priceLandTxt.setText("2799000");
                priceTxt.setText("2799000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            case 9:
                priceLandTxt.setText("4999000");
                priceTxt.setText("4999000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;  
            default:
                priceLandTxt.setText("3449000");
                priceTxt.setText("3449000");
                DPTxt.setText("");
                installmentAmountTxt.setText("");
                installmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
        }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        DPTxt.setText("");
        installmentAmountTxt.setText("");
        installmentMonthTxt.setText("");
        ppnTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        agreementCbx.setSelected(false);
        priceTxt.setText("");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        if(priceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilihan belum lengkap");
        } else if(DPTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP harus diisi");
        } else if(installmentAmountTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi Jumlah cicilan yang diinginkan");
        } else {
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    dp = Long.parseLong(DPTxt.getText()),
                    installmentAmount = Long.parseLong(installmentAmountTxt.getText()),
                    ppn, installmentPerMonth;
            ppn = landPrice * 10 / 100;
            installmentPerMonth = (landPrice + ppn) / installmentAmount;
            ppnTxt.setText("" + ppn);
            installmentMonthTxt.setText("" + installmentPerMonth);
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if(orderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi");
            agreementCbx.setSelected(false);
        } else if ( ppnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "tekan tombol proses terlebih dahulu");
            agreementCbx.setSelected(false);
        } else if(agreementCbx.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Pemesan menyetujui");
            agreementCbx.setSelected(true);
        } else{
            JOptionPane.showMessageDialog(null, "pesanan belum di setujui");
            agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed

    @SuppressWarnings("empty-statement")
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(agreementCbx.isSelected() == false){
            JOptionPane.showMessageDialog(null, 
                    "Klik centang checkbox untuk simpan data", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                
                String sql = "INSERT INTO handphone (name, tipe, harga, jumlah_cicilan, cicilan_bulan) VALUES ('"
                        + orderNameTxt.getText() + "','"
                        + areaCombobox.getSelectedItem() + "','"
                        + priceTxt.getText() + "','"
                        + installmentAmountTxt.getText() + "','"
                        + installmentMonthTxt.getText() + "')";
                Connection c = Koneksi.getKoneksi();
                PreparedStatement s = c.prepareStatement(sql);
                s.execute();
            } catch(SQLException e){
               Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            option option = new option();
            option.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        option option = new option();
        option.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        ImageIcon b = new ImageIcon(getClass().getResource("images/kembali22.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        ImageIcon b = new ImageIcon(getClass().getResource("images/kembali2.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        ImageIcon b = new ImageIcon(getClass().getResource("images/kembali2.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased
        ImageIcon b = new ImageIcon(getClass().getResource("images/kembali22.png"));
        jButton1.setIcon(b);
    }//GEN-LAST:event_jButton1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPTxt;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField installmentAmountTxt;
    private javax.swing.JTextField installmentMonthTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JButton processButton;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private Object getDesktopPane() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
